name: CwCrop
author: mario_fischer
category: Media
tags: [images, crop, pictures]
#docs: http://www.chipwreck.de/blog/2009/10/26/javascript-only-image-crop/
#demo: http://www.chipwreck.de/cwcrop/crop_test.php
#current: 0.6

